version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /packages/ghaf-mem-manager
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /packages/ghaf-nw-packet-forwarder
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /packages/vinotify/vinotify
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /packages/go/swtpm-proxy-shim
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /packages/rust/ghaf-mem-manager
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /packages/rust/ghaf-nw-packet-forwarder
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /packages/rust/ghaf-kill-switch-app
    schedule:
      interval: weekly
