# Copyright 2022-2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "ghafpkgs"
SPDX-PackageSupplier = "Technology Innovation Institute <https://tii.ae>"
SPDX-PackageDownloadLocation = "https://github.com/tiiuae/ghaf"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2022-2025 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
  "flake.lock",
  "packages/ghaf-mem-manager/Cargo.lock",
  "packages/ghaf-artwork/**/*.png",
  "packages/ghaf-artwork/**/*.jpg",
  "packages/ghaf-artwork/**/*.svg",
  "packages/ghaf-theme/**/*.svg",
  "packages/ghaf-nw-packet-forwarder/Cargo.lock",
  "packages/ghaf-nw-packet-forwarder/flake.lock",
]

[[annotations]]
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "2022-2024 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
  "docs/**/*.svg", "docs/**/*.png",
]

# External code
