# Copyright 2022-2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "ghafpkgs"
SPDX-PackageSupplier = "Technology Innovation Institute <https://tii.ae>"
SPDX-PackageDownloadLocation = "https://github.com/tiiuae/ghaf"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2022-2024 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
	"flake.lock",
  "packages/ghaf-artwork/**/*.png",
  "packages/ghaf-artwork/**/*.svg",
  "packages/ghaf-theme/**/*.svg",
]

[[annotations]]
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "2022-2024 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
	"docs/**/*.svg", "docs/**/*.png",
]

# External code
