# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

[package]
name = "nw-pckt-fwd"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
#build = "./custom_task/generate_compile_time_info.rs"

[dependencies]
pnet = "0.35"
tokio = { version = "1.48.0", features = ["full", "tracing"] }
tokio-util = "0.7.17"
clap = { version = "4.5.53", features = ["derive"] }
lazy_static = "1.5.0"

# Logging
log = "0.4.29"
env_logger = "0.11.8"
syslog = "7.0.0"
tracing = { version = "0.1.44", optional = true }
tracing-subscriber = { version = "0.3.22", optional = true }
console-subscriber = { version = "0.5.0", optional = true }

[build-dependencies]
chrono = "0.4.42"

[features]
# Feature to enable tokio-console
tokio-console = ["console-subscriber"]
