# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ghaf-mem-managerd"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.49", features = ["rt", "net", "macros", "fs", "time", "io-util", "signal", "sync"] }
tracing = "0.1"
tracing-subscriber = "0.3"
zbus = { version = "5.12.0", default-features = false, features = ["tokio"] }

[dev-dependencies]
tempfile = "3.24"
