# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hotplug"
version = "1.0.0"
description = "Qemu hotplug helper for PCI and USB devices"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "TII (SSRC) and the Ghaf contributors"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Systems Administration",
]
requires-python = ">=3.11"
dependencies = [
    "qemu.qmp>=0.0.5",
    "systemd-python>=235",
]

[project.scripts]
hotplug = "hotplug.main:main"

[tool.hatch.build.targets.wheel]
packages = ["hotplug/hotplug"]

[dependency-groups]
dev = []
